name: 自动化处理 Minecraft 的主要API

on:
  schedule:
    - cron: '0 0 * * 0'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  # 任务 1: 创建草稿 Release (已增加自动清理功能)
  create-draft:
    runs-on: ubuntu-latest
    outputs:
      tag: weekly-${{ env.TAG_DATE }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Get current date
        id: date
        run: echo "TAG_DATE=$(date +'%Y-%m-%d')" >> $GITHUB_ENV
      
      # 新增步骤: 尝试删除前一次失败留下的同名 Release/Tag
      - name: Clean up previous failed run
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          TAG="weekly-${{ env.TAG_DATE }}"
          echo "Checking for and deleting existing release with tag $TAG"
          # 删除 Release，如果存在的话。--yes 会跳过确认
          gh release delete "$TAG" --yes || echo "No previous release to delete."
          # 删除关联的 Git 标签，如果存在的话
          git push origin --delete "$TAG" || echo "No previous tag to delete."

      - name: Create Draft Release
        id: create_release
        uses: softprops/action-gh-release@v2
        with:
          name: ${{ env.TAG_DATE }}
          tag_name: weekly-${{ env.TAG_DATE }}
          body: |
            Automated weekly collection of Minecraft modding development kits. This release is built incrementally and in parallel.
            - **Forge**: Per-MC-version archives.
            - **Fabric**: Installer and Per-MC-Version-group API archives.
            - **NeoForge**: Per-Major.Minor-version-group archives from the Maven repository.
          draft: true

  # ... 其他所有任务 (process-forge, process-fabric, process-neoforge, publish-release) 保持完全不变 ...
  # (为了简洁，省略了后面重复的代码，您只需替换 create-draft 任务即可)
