name: 自动化的对 Minecraft 的主要 API 进行 Dump

on:
  schedule:
    - cron: '0 0 * * 0'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  # 任务 1: 创建草稿 Release (已增加自动清理功能)
  create-draft:
    runs-on: ubuntu-latest
    outputs:
      tag: weekly-${{ env.TAG_DATE }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Get current date
        id: date
        run: echo "TAG_DATE=$(date +'%Y-%m-%d')" >> $GITHUB_ENV
      
      # 新增步骤: 尝试删除前一次失败留下的同名 Release/Tag
      - name: Clean up previous failed run
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          TAG="weekly-${{ env.TAG_DATE }}"
          echo "Checking for and deleting existing release with tag $TAG"
          # 删除 Release，如果存在的话。--yes 会跳过确认
          gh release delete "$TAG" --yes || echo "No previous release to delete."
          # 删除关联的 Git 标签，如果存在的话
          git push origin --delete "$TAG" || echo "No previous tag to delete."

      - name: Create Draft Release
        id: create_release
        uses: softprops/action-gh-release@v2
        with:
          name: ${{ env.TAG_DATE }}
          tag_name: weekly-${{ env.TAG_DATE }}
          body: |
            Automated weekly collection of Minecraft modding development kits. This release is built incrementally and in parallel.
            - **Forge**: Per-MC-version archives.
            - **Fabric**: Installer and Per-MC-Version-group API archives.
            - **NeoForge**: Per-Major.Minor-version-group archives from the Maven repository.
          draft: true

  # 任务 2: 并行处理 Forge
  process-forge:
    runs-on: ubuntu-latest
    needs: create-draft
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Process and Upload Forge Incrementally
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TAG: ${{ needs.create-draft.outputs.tag }}
        run: |
          echo "--- Starting Forge Incremental Processing (wget mode) ---"
          INDEX_PAGES=$(curl -s https://files.minecraftforge.net/net/minecraftforge/forge/ | grep -oP 'href="(index_[^"]+\.html)"' | sed 's/href="\([^"]*\)"/\1/')
          
          for page in $INDEX_PAGES; do
            MC_VERSION=$(echo "$page" | sed -e 's/index_//' -e 's/\.html//')
            echo "--- Processing Forge for MC Version: $MC_VERSION ---"
            
            TEMP_DIR="forge_temp_${MC_VERSION}"
            mkdir -p "$TEMP_DIR"
            
            PAGE_URL="https://files.minecraftforge.net/net/minecraftforge/forge/$page"
            curl -s "$PAGE_URL" | grep -oP 'https://adfoc\.us/serve/sitelinks/[^"]+' | grep -iE 'installer|mdk|src|universal' | sort -u | sed -n 's/.*url=\(.*\)/\1/p' | while read -r DOWNLOAD_URL; do
              if [[ -n "$DOWNLOAD_URL" ]]; then
                FILENAME=$(basename "$DOWNLOAD_URL")
                echo "Downloading: $FILENAME"
                wget -P "$TEMP_DIR/" "$DOWNLOAD_URL" || echo "  -> Download failed: $FILENAME"
              fi
            done

            if [ -z "$(ls -A "$TEMP_DIR")" ]; then
              echo "No files downloaded for $MC_VERSION, skipping."
              rm -rf "$TEMP_DIR"
              continue
            fi
            
            ARCHIVE_NAME="forge-${MC_VERSION}.tar.xz"
            echo "Archiving to $ARCHIVE_NAME"
            tar --use-compress-program="xz -T0" -cvf "$ARCHIVE_NAME" -C "$TEMP_DIR" .
            
            echo "Uploading $ARCHIVE_NAME"
            gh release upload "$TAG" "$ARCHIVE_NAME" --clobber
            
            echo "Cleaning up local files for $MC_VERSION"
            rm -rf "$TEMP_DIR" "$ARCHIVE_NAME"
          done

  # 任务 3: 并行处理 Fabric
  process-fabric:
    runs-on: ubuntu-latest
    needs: create-draft
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Process and Upload Fabric Incrementally
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TAG: ${{ needs.create-draft.outputs.tag }}
        run: |
          echo "--- Starting Fabric Incremental Processing ---"
          # 步骤 1: 单独处理 Installer
          echo "Processing Fabric Installer..."
          INSTALLER_VERSION=$(curl -s https://maven.fabricmc.net/net/fabricmc/fabric-installer/maven-metadata.xml | grep -oP '<latest>\K[^<]+')
          INSTALLER_URL="https://maven.fabricmc.net/net/fabricmc/fabric-installer/${INSTALLER_VERSION}/fabric-installer-${INSTALLER_VERSION}.jar"
          TEMP_DIR_INSTALLER="fabric_installer_temp"
          mkdir -p "$TEMP_DIR_INSTALLER"
          wget -P "$TEMP_DIR_INSTALLER/" "$INSTALLER_URL"
          ARCHIVE_NAME_INSTALLER="fabric-installer.tar.xz"
          tar --use-compress-program="xz -T0" -cvf "$ARCHIVE_NAME_INSTALLER" -C "$TEMP_DIR_INSTALLER" .
          echo "Uploading $ARCHIVE_NAME_INSTALLER"
          gh release upload "$TAG" "$ARCHIVE_NAME_INSTALLER" --clobber
          rm -rf "$TEMP_DIR_INSTALLER" "$ARCHIVE_NAME_INSTALLER"
          
          # 步骤 2: 分组处理 API
          echo "--- Group Processing for Fabric APIs ---"
          ALL_TAGS=$(gh release list -R FabricMC/fabric -L 2000 --json tagName -q '.[].tagName')
          MC_VERSION_GROUPS=$(echo "$ALL_TAGS" | grep -oP '\+\K\d+\.\d+' | sort -u)
          
          for GROUP in $MC_VERSION_GROUPS; do
            echo "--- Processing Fabric API Group for MC: $GROUP ---"
            TEMP_DIR_API="fabric_api_temp_${GROUP//./_}"
            mkdir -p "$TEMP_DIR_API"
            
            for FULL_TAG in $(echo "$ALL_TAGS" | grep "+${GROUP}"); do
              echo "  -> Found tag: $FULL_TAG"
              gh release download "$FULL_TAG" -R FabricMC/fabric -p 'fabric-api-*.jar' --dir "$TEMP_DIR_API" --clobber || echo "     - No assets found for $FULL_TAG"
            done
            
            if [ -z "$(ls -A "$TEMP_DIR_API")" ]; then
              echo "No files downloaded for group $GROUP, skipping."
              rm -rf "$TEMP_DIR_API"
              continue
            fi
            
            ARCHIVE_NAME_API="fabric-api-${GROUP}.tar.xz"
            echo "Archiving to $ARCHIVE_NAME_API"
            tar --use-compress-program="xz -T0" -cvf "$ARCHIVE_NAME_API" -C "$TEMP_DIR_API" .
            
            echo "Uploading $ARCHIVE_NAME_API"
            gh release upload "$TAG" "$ARCHIVE_NAME_API" --clobber
            
            echo "Cleaning up local files for group $GROUP"
            rm -rf "$TEMP_DIR_API" "$ARCHIVE_NAME_API"
          done
  
  # 任务 4: 并行处理 NeoForge
  process-neoforge:
    runs-on: ubuntu-latest
    needs: create-draft
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Process and Upload NeoForge by Version Group
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TAG: ${{ needs.create-draft.outputs.tag }}
        run: |
          echo "--- Starting NeoForge Group Processing ---"
          ALL_VERSIONS=$(curl -s "https://maven.neoforged.net/releases/net/neoforged/neoforge/maven-metadata.xml" | grep -oP '<version>\K[^<]+')
          VERSION_GROUPS=$(echo "$ALL_VERSIONS" | cut -d'.' -f1,2 | sort -u)
          
          for GROUP in $VERSION_GROUPS; do
            echo "--- Processing NeoForge Group: $GROUP ---"
            TEMP_DIR="neoforge_temp_${GROUP}"
            mkdir -p "$TEMP_DIR"
            for FULL_VERSION in $(echo "$ALL_VERSIONS" | grep "^${GROUP}"); do
              echo "  -> Found version: $FULL_VERSION"
              INSTALLER_URL="https://maven.neoforged.net/releases/net/neoforged/neoforge/${FULL_VERSION}/neoforge-${FULL_VERSION}-installer.jar"
              UNIVERSAL_URL="https://maven.neoforged.net/releases/net/neoforged/neoforge/${FULL_VERSION}/neoforge-${FULL_VERSION}-universal.jar"
              wget -P "$TEMP_DIR/" "$INSTALLER_URL" || echo "     - No installer found for $FULL_VERSION"
              wget -P "$TEMP_DIR/" "$UNIVERSAL_URL" || echo "     - No universal found for $FULL_VERSION"
            done
            if [ -z "$(ls -A "$TEMP_DIR")" ]; then rm -rf "$TEMP_DIR"; continue; fi
            ARCHIVE_NAME="neoforge-${GROUP}.tar.xz"
            tar --use-compress-program="xz -T0" -cvf "$ARCHIVE_NAME" -C "$TEMP_DIR" .
            gh release upload "$TAG" "$ARCHIVE_NAME" --clobber
            rm -rf "$TEMP_DIR" "$ARCHIVE_NAME"
          done

  # 任务 5: 发布 Release
  publish-release:
    runs-on: ubuntu-latest
    needs: [process-forge, process-fabric, process-neoforge]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Publish Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ needs.create-draft.outputs.tag }}
          draft: false
