name: 自动化的对 Minecraft 的主要 API 进行 Dump

on:
  schedule:
    - cron: '0 0 * * 0'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  create-draft:
    runs-on: ubuntu-latest
    outputs:
      tag: weekly-${{ env.TAG_DATE }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Get current date
        id: date
        run: echo "TAG_DATE=$(date +'%Y-%m-%d')" >> $GITHUB_ENV
      - name: Clean up previous failed run
        env:
          # 关键改动 1: 在需要与 API 交互的地方，使用新的 PAT
          GH_TOKEN: ${{ secrets.ACTION_PAT }}
        run: |
          TAG="weekly-${{ env.TAG_DATE }}"
          echo "Checking for and deleting existing release with tag $TAG"
          gh release delete "$TAG" --yes || echo "No previous release to delete."
          git push origin --delete "$TAG" || echo "No previous tag to delete."
      - name: Create Draft Release
        id: create_release
        uses: softprops/action-gh-release@v2
        with:
          name: ${{ env.TAG_DATE }}
          tag_name: weekly-${{ env.TAG_DATE }}
          body: |
            # ... body 内容不变 ...
          draft: true
          # 关键改动 2: 明确告诉 softprops/action-gh-release 使用 PAT
          token: ${{ secrets.ACTION_PAT }}

  process-forge:
    runs-on: ubuntu-latest
    needs: create-draft
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Process and Upload Forge Incrementally
        env:
          # 关键改动 3: 所有需要 gh 命令的任务都使用 PAT
          GH_TOKEN: ${{ secrets.ACTION_PAT }}
          TAG: ${{ needs.create-draft.outputs.tag }}
        run: |
          # ... Forge 的脚本完全不变 ...
          echo "--- Starting Forge Incremental Processing (wget mode) ---"
          INDEX_PAGES=$(curl -s https://files.minecraftforge.net/net/minecraftforge/forge/ | grep -oP 'href="(index_[^"]+\.html)"' | sed 's/href="\([^"]*\)"/\1/')
          for page in $INDEX_PAGES; do
            MC_VERSION=$(echo "$page" | sed -e 's/index_//' -e 's/\.html//')
            echo "--- Processing Forge for MC Version: $MC_VERSION ---"
            TEMP_DIR="forge_temp_${MC_VERSION}"
            mkdir -p "$TEMP_DIR"
            PAGE_URL="https://files.minecraftforge.net/net/minecraftforge/forge/$page"
            curl -s "$PAGE_URL" | grep -oP 'https://adfoc\.us/serve/sitelinks/[^"]+' | grep -iE 'installer|mdk|src|universal' | sort -u | sed -n 's/.*url=\(.*\)/\1/p' | while read -r DOWNLOAD_URL; do
              if [[ -n "$DOWNLOAD_URL" ]]; then
                FILENAME=$(basename "$DOWNLOAD_URL")
                echo "Downloading: $FILENAME"
                wget -nv -P "$TEMP_DIR/" "$DOWNLOAD_URL" || echo "  -> FAILED: $FILENAME"
              fi
            done
            if [ -z "$(ls -A "$TEMP_DIR")" ]; then rm -rf "$TEMP_DIR"; continue; fi
            ARCHIVE_NAME="forge-${MC_VERSION}.tar.xz"
            tar --use-compress-program="xz -T0" -cvf "$ARCHIVE_NAME" -C "$TEMP_DIR" .
            gh release upload "$TAG" "$ARCHIVE_NAME" --clobber
            rm -rf "$TEMP_DIR" "$ARCHIVE_NAME"
          done

  process-fabric:
    runs-on: ubuntu-latest
    needs: create-draft
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Process and Upload Fabric Incrementally
        env:
          # 关键改动 4: Fabric 任务尤其需要 PAT
          GH_TOKEN: ${{ secrets.ACTION_PAT }}
          TAG: ${{ needs.create-draft.outputs.tag }}
        run: |
          # ... Fabric 的脚本完全不变 ...
          echo "--- Starting Fabric Incremental Processing ---"
          echo "Processing Fabric Installer..."
          INSTALLER_VERSION=$(curl -s https://maven.fabricmc.net/net/fabricmc/fabric-installer/maven-metadata.xml | grep -oP '<latest>\K[^<]+')
          INSTALLER_URL="https://maven.fabricmc.net/net/fabricmc/fabric-installer/${INSTALLER_VERSION}/fabric-installer-${INSTALLER_VERSION}.jar"
          TEMP_DIR_INSTALLER="fabric_installer_temp"
          mkdir -p "$TEMP_DIR_INSTALLER"
          wget -nv -P "$TEMP_DIR_INSTALLER/" "$INSTALLER_URL"
          ARCHIVE_NAME_INSTALLER="fabric-installer.tar.xz"
          tar --use-compress-program="xz -T0" -cvf "$ARCHIVE_NAME_INSTALLER" -C "$TEMP_DIR_INSTALLER" .
          echo "Uploading $ARCHIVE_NAME_INSTALLER"
          gh release upload "$TAG" "$ARCHIVE_NAME_INSTALLER" --clobber
          rm -rf "$TEMP_DIR_INSTALLER" "$ARCHIVE_NAME_INSTALLER"
          echo "--- Group Processing for Fabric APIs ---"
          ALL_TAGS=$(gh release list -R FabricMC/fabric -L 2000 --json tagName -q '.[].tagName')
          MC_VERSION_GROUPS=$(echo "$ALL_TAGS" | grep -oP '\+\K\d+\.\d+' | sort -u)
          for GROUP in $MC_VERSION_GROUPS; do
            echo "--- Processing Fabric API Group for MC: $GROUP ---"
            TEMP_DIR_API="fabric_api_temp_${GROUP//./_}"
            mkdir -p "$TEMP_DIR_API"
            for FULL_TAG in $(echo "$ALL_TAGS" | grep "+${GROUP}"); do
              echo "  -> Found tag: $FULL_TAG"
              gh release download "$FULL_TAG" -R FabricMC/fabric -p 'fabric-api-*.jar' --dir "$TEMP_DIR_API" --clobber || echo "     - No assets found for $FULL_TAG"
            done
            if [ -z "$(ls -A "$TEMP_DIR_API")" ]; then rm -rf "$TEMP_DIR_API"; continue; fi
            ARCHIVE_NAME_API="fabric-api-${GROUP}.tar.xz"
            tar --use-compress-program="xz -T0" -cvf "$ARCHIVE_NAME_API" -C "$TEMP_DIR_API" .
            echo "Uploading $ARCHIVE_NAME_API"
            gh release upload "$TAG" "$ARCHIVE_NAME_API" --clobber
            rm -rf "$TEMP_DIR_API" "$ARCHIVE_NAME_API"
          done
  
  process-neoforge:
    runs-on: ubuntu-latest
    needs: create-draft
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Process and Upload NeoForge by Version Group
        env:
          # 关键改动 5: NeoForge 任务也使用 PAT
          GH_TOKEN: ${{ secrets.ACTION_PAT }}
          TAG: ${{ needs.create-draft.outputs.tag }}
        run: |
          # ... NeoForge 的脚本完全不变 ...
          echo "--- Starting NeoForge Group Processing ---"
          ALL_VERSIONS=$(curl -s "https://maven.neoforged.net/releases/net/neoforged/neoforge/maven-metadata.xml" | grep -oP '<version>\K[^<]+')
          VERSION_GROUPS=$(echo "$ALL_VERSIONS" | cut -d'.' -f1,2 | sort -u)
          for GROUP in $VERSION_GROUPS; do
            echo "--- Processing NeoForge Group: $GROUP ---"
            TEMP_DIR="neoforge_temp_${GROUP}"
            mkdir -p "$TEMP_DIR"
            for FULL_VERSION in $(echo "$ALL_VERSIONS" | grep "^${GROUP}"); do
              echo "  -> Downloading files for version: $FULL_VERSION"
              INSTALLER_URL="https://maven.neoforged.net/releases/net/neoforged/neoforge/${FULL_VERSION}/neoforge-${FULL_VERSION}-installer.jar"
              UNIVERSAL_URL="https://maven.neoforged.net/releases/net/neoforged/neoforge/${FULL_VERSION}/neoforge-${FULL_VERSION}-universal.jar"
              wget -nv -P "$TEMP_DIR/" "$INSTALLER_URL" || echo "     - FAILED: Installer for $FULL_VERSION"
              wget -nv -P "$TEMP_DIR/" "$UNIVERSAL_URL" || echo "     - FAILED: Universal for $FULL_VERSION"
            done
            if [ -z "$(ls -A "$TEMP_DIR")" ]; then rm -rf "$TEMP_DIR"; continue; fi
            ARCHIVE_NAME="neoforge-${GROUP}.tar.xz"
            tar --use-compress-program="xz -T0" -cvf "$ARCHIVE_NAME" -C "$TEMP_DIR" .
            gh release upload "$TAG" "$ARCHIVE_NAME" --clobber
            rm -rf "$TEMP_DIR" "$ARCHIVE_NAME"
          done

  publish-release:
    runs-on: ubuntu-latest
    needs: [process-forge, process-fabric, process-neoforge]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Publish Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ needs.create-draft.outputs.tag }}
          draft: false
          # 关键改动 6: 发布时也使用 PAT
          token: ${{ secrets.ACTION_PAT }}
